osx_image: xcode10.1
language: swift

script:
  - set -o pipefail
  - xcodebuild test -enableCodeCoverage YES -project MemoryCache.xcodeproj -scheme MemoryCacheTests -sdk iphonesimulator | xcpretty -c
  - pod lib lint
